name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu       , use-cross: false }
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl      , use-cross: true  }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-gnueabihf  , use-cross: true  }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-musleabihf , use-cross: true  }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract crate information
        shell: bash
        run: |
          echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --release --target ${{ matrix.job.target }}
      - name: Archive
        shell: bash
        run: |
          cd target/${{ matrix.job.target }}/release
          tar zxvf ${{ env.PROJECT_NAME }}_{{ matrix.job.target }}.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files: |
            target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}_{{ matrix.job.target }}.tar.gz
